// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvAOj8GjYy9uzOR8bLYyrgHparwLSeAY',
    appId: '1:1052954263686:web:4caf6f6fbe0341beafd107',
    messagingSenderId: '1052954263686',
    projectId: 'restaurant-app-36933',
    authDomain: 'restaurant-app-36933.firebaseapp.com',
    storageBucket: 'restaurant-app-36933.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHvR_5279_hLdQT1B5xySzJjT310nGlc',
    appId: '1:1052954263686:android:36d2a47e7075cdc3afd107',
    messagingSenderId: '1052954263686',
    projectId: 'restaurant-app-36933',
    storageBucket: 'restaurant-app-36933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxiwavxOC2M8L_SrBG5osuGPMfIhiTfD4',
    appId: '1:1052954263686:ios:6f2028f9a4a5f423afd107',
    messagingSenderId: '1052954263686',
    projectId: 'restaurant-app-36933',
    storageBucket: 'restaurant-app-36933.appspot.com',
    iosClientId:
        '1052954263686-b3k5l63rbavg6ee6k2rodbc46b61j1h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxiwavxOC2M8L_SrBG5osuGPMfIhiTfD4',
    appId: '1:1052954263686:ios:6f2028f9a4a5f423afd107',
    messagingSenderId: '1052954263686',
    projectId: 'restaurant-app-36933',
    storageBucket: 'restaurant-app-36933.appspot.com',
    iosClientId:
        '1052954263686-b3k5l63rbavg6ee6k2rodbc46b61j1h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );
}
